### ISSUE TITLE
Scan Button not working properly.

### ISSUE THREAD

**Issue by sergiomr88** [aconno/AcnSensaDroid#14]
The Scan Button does not work properly if the MainActivity is started during scanning. It shows "Scan" instead of the correct message "Stop Scanning".

**Comment by borna-mdn** [comment]
Fixed by adding a static boolean flag: isRunning() in BluetoothScanningService.
Depending on if the BluetoothScanningService is running, the "Scan" button in MainActivity will have a corresponding title.
