### ISSUE TITLE
Google Cloud integration

### ISSUE THREAD

**Issue by borna-mdn** [aconno/AcnSensaDroid#25]
In settings screen, add new section: Google Cloud integration.

When Google Cloud integration enabled (and configured), AcnSensa will push all sensor values to Google Cloud IoT Core platform. The protocol for sending the data is MQTT.

Settings screen needs to contain all configuration settings required for successfully sending data to Google Cloud.

**Comment by SerhatSurguvec** [comment]
Google Cloud integration completed.
